'use client';

import Link from 'next/link';
import { useAuth } from '@/context/AuthContext';
import { ArrowRight, Sparkles } from 'lucide-react';
import { PublicNavbar } from '@/components/layout/PublicNavbar';

export default function LandingPage() {
  const { token } = useAuth();

  return (
    <div className="min-h-screen bg-background flex flex-col font-sans relative overflow-hidden">
      {/* Subtle background glow for premium feel */}
      <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-orange-100/40 dark:bg-orange-900/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-blue-100/40 dark:bg-blue-900/10 rounded-full blur-3xl pointer-events-none" />

      <PublicNavbar />

      <main className="flex-1 flex flex-col items-center justify-center px-6 max-w-5xl mx-auto w-full relative z-10 -mt-10">
        <div className="flex items-center gap-2 px-4 py-2 rounded-full border border-border/50 bg-secondary/30 mb-8 backdrop-blur-sm">
          <Sparkles className="w-4 h-4 text-orange-500" />
          <span className="text-sm font-medium text-muted-foreground">The next generation of presentations</span>
        </div>

        <h1 className="text-5xl md:text-[5rem] lg:text-[6rem] font-serif font-medium tracking-tight text-center mb-8 text-foreground leading-[1.05]">
          Presentations,<br />
          <span className="text-muted-foreground">generated by AI.</span>
        </h1>
        
        <p className="text-lg md:text-xl text-muted-foreground text-center max-w-2xl mb-12 leading-relaxed">
          Transform your ideas into beautiful, professional slides in seconds. Auto-PPT plans, designs, and refines your presentations autonomously.
        </p>

        <div className="flex flex-col sm:flex-row items-center gap-4">
          <Link
            href={token ? '/dashboard' : '/register'}
            className="group px-8 py-4 bg-foreground text-background rounded-full font-medium text-lg hover:bg-foreground/90 transition-all shadow-md hover:shadow-lg hover:-translate-y-0.5 flex items-center gap-2"
          >
            {token ? 'Open Dashboard' : 'Start for free'}
            <ArrowRight className="w-5 h-5 transition-transform group-hover:translate-x-1" />
          </Link>
          {!token && (
            <Link
              href="/login"
              className="px-8 py-4 border border-border rounded-full font-medium text-lg hover:bg-secondary/50 transition-colors"
            >
              Sign in to account
            </Link>
          )}
        </div>

        <div className="mt-24 w-full grid grid-cols-1 md:grid-cols-3 gap-8 pt-12 border-t border-border/40">
          <div className="flex flex-col items-center text-center">
            <div className="w-12 h-12 bg-secondary rounded-2xl flex items-center justify-center mb-4">
              <span className="text-xl font-serif">1</span>
            </div>
            <h3 className="text-lg font-semibold mb-2">Write your idea</h3>
            <p className="text-muted-foreground text-sm">Simply describe what you want to present. No formatting needed.</p>
          </div>
          <div className="flex flex-col items-center text-center">
            <div className="w-12 h-12 bg-secondary rounded-2xl flex items-center justify-center mb-4">
              <span className="text-xl font-serif">2</span>
            </div>
            <h3 className="text-lg font-semibold mb-2">AI plans it out</h3>
            <p className="text-muted-foreground text-sm">Our agentic logic builds a highly structured narrative layout.</p>
          </div>
          <div className="flex flex-col items-center text-center">
            <div className="w-12 h-12 bg-secondary rounded-2xl flex items-center justify-center mb-4">
              <span className="text-xl font-serif">3</span>
            </div>
            <h3 className="text-lg font-semibold mb-2">Download & present</h3>
            <p className="text-muted-foreground text-sm">Get a fully designed PowerPoint file instantly. Ready to share.</p>
          </div>
        </div>
      </main>
      
      <footer className="py-8 text-center text-sm text-muted-foreground/60 border-t border-border/40 mt-12 bg-background/50 backdrop-blur-md relative z-10 w-full">
        <div className="max-w-7xl mx-auto px-8 flex justify-between items-center">
           <span>&copy; {new Date().getFullYear()} Auto-PPT.</span>
           <span className="font-serif italic">Agentic flow</span>
        </div>
      </footer>
    </div>
  );
}
